name: Deployment to production

on: [push]
#
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR

        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sid_backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t sid_backend .
          docker tag sid_backend:latest 675735647272.dkr.ecr.ap-southeast-1.amazonaws.com/sid_backend:latest
          docker push 675735647272.dkr.ecr.ap-southeast-1.amazonaws.com/sid_backend:latest
